config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, :controllers => {
    sessions: 'users/sessions',
    registrations: 'registrations'
  }  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "authors#index"
  resources :authors
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :trackable, :lockable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @author = Author.new
    @books = Book.all
  end

  def create
    @author = Author.create(author_params)
    if params[:books].present?
      params[:books].each do |id|
        @author.books << Book.find(id)
      end
    end
    if @author.save
      redirect_to @author
    else
      render 'new'
    end
  end

  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  private

  def author_params
    params.require(:author).permit(:name, :dob)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @author = Author.find(params[:book][:author_id])
    @book = @author.books.create(book_params)
    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  end

  def index
  end

  def show
    @book = Book.find(params[:id])
  end

  private

  def book_params
    params.require(:book).permit(:title,:isbn)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  respond_to :json
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  respond_to :json, :js
  # before_action :configure_sign_in_params, only: [:create]
  # after_action :set_csrf_headers, only: :create

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    puts "here"
    resource = User.find_for_database_authentication(email: params[:user][:email])
    return invalid_login_attempt unless resource

    if resource.valid_password?(params[:user][:password])
      puts "in jhhhhhhhhhhere"
      sign_in :user, resource
      # respond_to do |format|
      #   puts format
      #   format.html { return redirect_to root_url }
      #   format.json { render json: true, status: 201 }
      # end
      return render json: true, status: 201
    end

    invalid_login_attempt
    # respond_to do |format|
    #   format.html
    #   format.js
    # end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def invalid_login_attempt
    set_flash_message(:alert, :invalid)
    render json: flash[:alert], status: 401
  end

  # def set_csrf_headers
  #   if request.xhr?
  #     # Add the newly created csrf token to the page headers
  #     # These values are sent on 1 request only
  #     response.headers['X-CSRF-Token'] = "#{form_authenticity_token}"
  #     response.headers['X-CSRF-Param'] = "#{request_forgery_protection_token}"
  #   end
  # end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/index.html.erb
<div class="container">
  <div class = "mb-4" >
    <%= link_to "New Author", new_author_path, class: "btn btn-primary btn-lg" %>
  </div>
  <% @authors.each do |author| %>
    <div class="card mb-4" style="width: 100%;">
      <div class="card-body">
        <h5 class="card-title"><%= author.name %></h5>
        <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="card-link">
          <%= link_to "Author Details", author_path(author) %>
        </a>
      </div>
    </div>
  <% end %>
</div>

app/views/authors/new.html.erb
<div class = "container">
  <%= form_with(model: @author, local: true) do |f| %>
    <p>
      <%= f.label :name, "Name" %>
      <%= f.text_field :name %>  
    </p>
    <p>
      <%= f.label :date, "Date" %>
      <%= f.date_field :dob %> 
    </p>
    <p>
      <%= f.label :book, "Book" %>
      <%= select_tag "books", options_from_collection_for_select(@books, "id", "title"), multiple: true, prompt: "" %>
    </p>
    <p>
      <%= f.submit "Submit", :disable_with => 'Submiting...' %>
    </p>
  <% end %>  
</div>

app/views/authors/show.html.erb
<div class="container">
  <p>
    <h4>
     <%= @author.name %> 
    </h4>
    <p>
      <%= @author.dob %>
    </p>
    <p> Books Title
      <ul>
        <% @author.books.each do |book| %>
          <li>
            <%= book.title %>
          </li>
        <% end %>
      </ul>
    </p>
  </p>  
</div>

app/views/books/index.html.erb
<div class="container">
  <h1>Books#index</h1>
  <p>
    Find me in app/views/books/index.html.erb
  </p>
</div>

app/views/books/new.html.erb
<div class="container">
  <%= form_with(model: @book, local: true) do |f| %>
    <p>
      <%= f.label :title, "Title" %>
      <%= f.text_field :title %>  
    </p>
    <p>
      <%= f.label :isbn, "Isbn" %>
      <%= f.text_field :isbn %> 
    </p>
    <p>
      <%= f.label :author, "Author" %>
      <%= select("book", "author_id", Author.all.collect {|a| [ a.name, a.id ] }, { include_blank: true }) %>
    </p>
    <p>
      <%= f.submit "Submit", :disable_with => 'Submiting...' %>
    </p>
  <% end %>  
</div>

app/views/books/show.html.erb
<div class="container">
  <p>
    <h4>
     <%= @book.title %> 
    </h4>
    <p>
      <%= @book.isbn %>
    </p>
    <p>
      <%= @book.author.name %>
    </p>
  </p>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthorBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href= <%= root_path %> >Navbar</a>
      <span class="navbar-text">
        <%= link_to "Login", "#login", "data-toggle" => "modal", :class => 'btn btn-small' %>
        <%= link_to "Sign up", "#sign_up", "data-toggle" => "modal", :class => 'btn btn-small btn-success' %>
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </span>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert" role="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
      <%= render "welcome/login_modal" %>
      <%= render "welcome/sign_up_modal" %>
    </div>
  </body>
</html>

app/views/welcome/_login_modal.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Log In</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="js-error-block-login" class="alert alert-danger" style="display:none;">
        <ul></ul>
      </div>
      <div class="modal-body">
        <%= form_for(resource, :as => resource_name, :url => session_path(resource_name), remote: true, :html => { :id => "ajax_signin"}) do |f| %>
          <%= render "devise/shared/error_messages", resource: resource %>

          <div><%= f.label :email %><br />
            <%= f.email_field :email, :autofocus => true %>
          </div>

          <div>
            <%= f.label :password %><br />
            <%= f.password_field :password %>
          </div>

          <% if devise_mapping.rememberable? -%>
            <div>
              <%= f.check_box :remember_me %> <%= f.label :remember_me %>
            </div>
          <% end %>
          <%= f.submit "Sign in", :class => 'btn btn-small btn-success', id: "ajax_form" %>
        <% end %>
      </div>
      <div class="modal-footer">
        <%= link_to "Sign up", "#sign_up", "data-toggle" => "modal", :class => 'btn btn-small btn-success' %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_sign_up_modal.html.erb
<div class="modal fade" id="sign_up" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Sign Up</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name), :html => { :id => "ajax_signin"}) do |f| %>
          <%= render "devise/shared/error_messages", resource: resource %>

          <div class="field">
            <%= f.label :first_name %><br />
            <%= f.text_field :first_name, autofocus: true %>
          </div>

          <div class="field">
            <%= f.label :last_name %><br />
            <%= f.text_field :last_name, autofocus: true %>
          </div>

          <div class="field">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
          </div>

          <div class="field">
            <%= f.label :password %>
            <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: "new-password" %>
          </div>

          <div class="field">
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
          </div>

          <div class="actions">
            <%= f.submit "Sign up" %>
          </div>
        <% end %>
      </div>

      <div class="modal-footer">
        <%= render "devise/shared/links" %>
      </div>
    </div>
  </div>
</div>